### ISSUE TITLE
"undefined" from import when define function throws an exception

### ISSUE THREAD

**Issue by johnduffell** [cujojs/curl#289]
Hi guys, we are using curl as our module loader here at the Guardian. We have had a few reports from firefox users that things aren't working which we've narrowed down to a dependency being passed in as undefined.  This only seems to happen on firefox when I open it in a new tab!
I'm wondering if it's some kind of timing issue, but I'm not sure how to debug it despite being able to reproduce it semi reliably.

Steps to reproduce:
Firefox: 38.0.5
Also nightly: 41.0a1 (2015-06-29)
1. Open our website http://www.theguardian.com/uk
2. open a story in a new tab
3. if the adverts appear, close the tab and return to step 2
4. if the adverts don't appear, you should see a console error 'n is undefined'
In this case, n is minified from "config" on this line:
https://github.com/guardian/frontend/blob/master/static/src/javascripts/projects/common/modules/experiments/ab.js#L114

Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1178263

**Comment by unscriptable** [comment]
Thanks for the excellent bug report, @johnduffell!  

Which version of curl.js are you using?  Are you using any curl.js plugins, loader, or shims?  
Are you able to reproduce the bug when using un-minified source (just in case that reveals more info)?

**Comment by johnduffell** [comment]
Hi @unscriptable thanks for getting back to me so quickly!
we are using 0.8.9
We are using domReady plugin and a couple of dummy loaders which are just because we already compiled with requirejs.
You can see our config here if it helps: https://github.com/guardian/frontend/blob/139cf70cfa70add566c425080dbf1d8375ed47f2/common/app/views/fragments/javaScriptLaterSteps.scala.html#L206

**Comment by unscriptable** [comment]
FYI: I just reproduced the bug on Firefox 36.0.1 (early March 2015).  I'm less suspicious that the problem is a recent change to Firefox.  I guess it's possible that you just haven't heard bug reports until now?

It's fairly hard to debug this problem since I can't seem to find a way to reproduce the problem while I have any debug tools enabled.  As far as I can tell, the Firefox debugger won't automatically open when a new tab opens.  Firebug can do this, but I can't reproduce the problem when Firebug is installed.  :unamused: 

Perhaps the best way to solve this is to try to create a simple test case that produces the same symptom.  I may have some time to try to create a test case later today.  If you have some time to try to produce a simple test case, that would be great.

**Comment by johnduffell** [comment]
Yeah definitely possible, JS falling over causes such a variety of reported behaviour, we don't necessarily spot these things until we know the root cause.
I had the same trouble with opening the debugger but one of the other devs mentioned adding a ```debugger;``` statement to the code might trigger the tools.
I don't have a lot of time this afternoon, but I'll let you know if I can produce something.  Thanks, John

**Comment by johnduffell** [comment]
Hi @unscriptable we are still getting a few reports about this, have you had any further thoughts about it?  Thanks, John

**Comment by johnduffell** [comment]
We have discovered the problem!! [Something](https://github.com/guardian/frontend/blob/4f52e99cfb949529ffbac80116d625cc2b67a311/static/src/javascripts/projects/common/utils/detect.js#L443) that we were defining was throwing an exception on evaluation, so curl was returning undefined.

We didn't find it because curl is just swallowing errors and returning undefined - would it be possible to make curl throw the exception so at least we get a stack trace?

**Comment by OliverJAsh** [comment]
I believe curl silently logs the error because that exception becomes a rejected promise, and the Promise implementation in curl doesn't log unhandled promise rejections: https://github.com/cujojs/curl/blob/d814748b8f7927b0e5e66a0afa65aa1adfacbdc8/src/curl.js#L385

Outside of curl we are using a Promise polyfill that does console log unhandled rejections (when’s ES6 shim), so to get error logging you just need to cast the promise:

``` js
Promise.resolve(require(['foo']))
```

**Comment by unscriptable** [comment]
I think @OliverJAsh has the best solution, atm.
